-- MySQL Script generated by MySQL Workbench
-- Mon Feb  6 21:45:42 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `username` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NULL,
  `name` VARCHAR(100) NULL,
  `password` VARCHAR(16) NULL,
  `role` VARCHAR(50) NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`raspberry`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`raspberry` (
  `raspberry_id` VARCHAR(50) NOT NULL,
  `type` VARCHAR(50) NULL,
  `note` VARCHAR(50) NULL,
  PRIMARY KEY (`raspberry_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sensor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sensor` (
  `sensor_id` VARCHAR(50) NOT NULL,
  `sensor_name` VARCHAR(50) NULL,
  `sensor_port` VARCHAR(4) NULL,
  `actuator_name` VARCHAR(50) NULL,
  `actuator_port` VARCHAR(30) NULL,
  `raspberry_id` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`sensor_id`, `raspberry_id`),
  INDEX `fk_sensor_raspberry1_idx` (`raspberry_id` ASC) VISIBLE,
  CONSTRAINT `fk_sensor_raspberry1`
    FOREIGN KEY (`raspberry_id`)
    REFERENCES `mydb`.`raspberry` (`raspberry_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`log` (
  `log_id` INT NOT NULL,
  `value` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `date` TEXT NULL,
  `timestamp` TEXT NULL,
  `sensor_id` VARCHAR(50) NOT NULL,
  `raspberry_id` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`log_id`, `sensor_id`, `raspberry_id`),
  INDEX `fk_log_sensor1_idx` (`sensor_id` ASC, `raspberry_id` ASC) VISIBLE,
  CONSTRAINT `fk_log_sensor1`
    FOREIGN KEY (`sensor_id` , `raspberry_id`)
    REFERENCES `mydb`.`sensor` (`sensor_id` , `raspberry_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`error_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`error_log` (
  `sensor_id` VARCHAR(50) NOT NULL,
  `error_message` VARCHAR(45) NULL,
  PRIMARY KEY (`sensor_id`),
  CONSTRAINT `fk_error_log_sensor1`
    FOREIGN KEY (`sensor_id`)
    REFERENCES `mydb`.`sensor` (`sensor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
